/*Burger Builder*/
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_ERROR = 'GET_INGREDIENTS_ERROR';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';

/*Checkout*/
export const PURCHASE_BURGER_REQUEST = 'PURCHASE_BURGER_REQUEST';
export const PURCHASE_BURGER_ERROR = 'PURCHASE_BURGER_ERROR';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';

/*Orders*/

export const GET_ORDER_REQUEST ='GET_ORDER_REQUEST';
export const GET_ORDER_ERROR ='GET_ORDER_ERROR';
export const GET_ORDER_SUCCESS ='GET_ORDER_SUCCESS';